toy_app/urls.py
from django.urls import path
from . import views
app_name = 'my_app'
urlpatterns = [
    path('upload/<int:pk>', views.UserUpdateView.as_view(), name='upload'),
    path('<int:pk>', views.UserDetailView.as_view(), name='details'),
    path('imprimir_archivo', views.proc_dem_file, name="imprimir"),
    path('suavizar', views.funcion_dma, name="dma"),
    path('produc_list', views.ProductListView.as_view(), name='product_list'),
]

toyproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

from toy_app import views
from toy_app.models import User

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('api/data', views.get_data, name="api-data"),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.logout, {'next_page': '/'}, name='logout'),
    path('signup/', views.Register.as_view(), name='signup'),
    path('api/chart/data/', views.ChartData.as_view()),
    path('my_app/', include('toy_app.urls')),
]

toy_app/models.py
from django.contrib.auth.models import AbstractUser
from django.contrib.postgres.fields import ArrayField
from django.db import models
from django.urls import reverse

from toy_app.managers import UserManager


class User(AbstractUser):
    email = models.EmailField(unique=True)
    file_one = models.FileField(upload_to='csvfiles')
    file_two = models.FileField(upload_to='csvfiles')
    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    def get_absolute_url(self):
        return reverse("index")


class Product(models.Model):
    owner = models.ForeignKey('User', on_delete=models.CASCADE, related_name="productos")
    material = models.CharField(max_length=255, blank=False, null=False)
    oficina = models.CharField(max_length=255, blank=False, null=False)
    lote_prod = models.IntegerField(null=True)
    lote_orden = models.IntegerField(null=True)
    punto_reorden = models.IntegerField(null=True)
    texto_breve_material = models.CharField(max_length=255)
    demanda_promedio = models.IntegerField(default=0)
    tipo_de_producto = models.CharField(max_length=1, null=True)
    lead_time = models.IntegerField(null=True)
    valor_r = models.DecimalField(max_digits=4, decimal_places=3, null=True)
    valor_v = models.IntegerField(null=True)
    valor_B1 = models.IntegerField(null=True)
    valor_B2 = models.DecimalField(max_digits=4, decimal_places=3, null=True)
    valor_B3 = models.DecimalField(max_digits=4, decimal_places=3, null=True)
    valor_B4 = models.IntegerField(null=True)
    valor_k = models.DecimalField(max_digits=4, decimal_places=3, null=True)
    valor_a = models.IntegerField(null=True)
    valor_p1 = models.DecimalField(max_digits=4, decimal_places=3, null=True)
    valor_p2 = models.DecimalField(max_digits=4, decimal_places=3, null=True)
    valor_sl = models.IntegerField(null=True)
    valor_z = models.IntegerField(null=True)
    valor_R2 = models.IntegerField(null=True)
    valor_tbs = models.IntegerField(null=True)


class ProductDemand(models.Model):
    product = models.ForeignKey(Product, related_name='demands', on_delete=models.CASCADE)
    date = models.DateField()
    mes = models.IntegerField()
    anno = models.IntegerField()
    demand = models.IntegerField()

    def getKey(self):
        # pretty sure this does not work like this.
        return self.date



class PronosticoSES(models.Model):
    owner = models.ForeignKey(Product, related_name='SES', on_delete=models.CASCADE)
    monthly_demand = ArrayField(models.IntegerField(default=[0], null=True, blank=True, ))
    alpha = models.DecimalField(max_digits=3, decimal_places=3, default=0.91)


class PronosticoDMA(models.Model):
    owner = models.ForeignKey(Product, related_name='DMA', on_delete=models.CASCADE)
    demanda_dma = models.IntegerField()



class LoteEcoOrden(models.Model):
    owner = models.ForeignKey(Product, related_name='EOQ', on_delete=models.CASCADE)
    Q = models.DecimalField(max_digits=20, decimal_places=3, default=0)
    # c = owner.valor_v
    # h = owner.valor_r
    # k = owner.valor_a
    date = models.DateField(null=True)
    demand = models.IntegerField(null=True)
    costo_p = models.DecimalField(max_digits=20, decimal_places=3)
    mantener_inv = models.DecimalField(max_digits=20, decimal_places=3)


class PuntoReorden(models.Model):
    owner = models.ForeignKey(Product, related_name='reorden', on_delete=models.CASCADE)
    demand = models.IntegerField()
    date = models.DateField()
    reordenpoint = models.IntegerField()


class LoteEcoProd(models.Model):
    owner = models.ForeignKey(Product, related_name='EPQ', on_delete=models.CASCADE)
    date = models.DateField()
    Qprima = models.DecimalField(max_digits=20, decimal_places=3, default=0)

toy_app/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.forms import models

from toy_app.models import User


class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30)
    last_name = forms.CharField(max_length=30)
    email = forms.EmailField(max_length=254)

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email', 'password1', 'password2')


class UploadFilesForm(models.ModelForm):
    class Meta:
        model = User
        fields = ('file_one', 'file_two')

toy_app/views.py
from rest_framework.views import APIView
from rest_framework.response import Response
# from rest_framework import authentication, permissions
from django.contrib.auth.models import User
from django.http import JsonResponse

from datetime import datetime
from math import sqrt

from django.shortcuts import render, redirect
from django.views import View
from django.views.generic import UpdateView, DetailView, ListView
from django.contrib.auth.decorators import login_required

from toy_app import forms
from toy_app.models import User, ProductDemand, Product, \
    PronosticoSES, LoteEcoOrden, LoteEcoProd, PronosticoDMA

import json
import csv


def index(request):
    return render(request, 'toy_app/index.html')


class ProductListView(ListView):
    model = Product


class Register(View):
    form_class = forms.SignUpForm
    template = 'registration/signup.html'

    def get(self, request):
        # mostrar formulario de registro
        form = self.form_class()
        return render(request, self.template, {'form': form})

    def post(self, request):
        # procesar formulario de registro
        form = self.form_class(request.POST)

        if form.is_valid():
            user = form.save(commit=False)
            user.username = user.email
            user.save()

            return render(request, 'toy_app/index.html')
        else:
            print('error')
            print(form.errors)
            return render(request, self.template, {'form': form})


class UserUpdateView(UpdateView):
    fields = ("file_one", "file_two")
    model = User


class UserDetailView(DetailView):
    context_object_name = "product_detail"
    model = Product
    template_name = 'toy_app/User_detail_view.html'


@login_required
def proc_dem_file(request):
    demfile = request.user.file_one.path
    varfile = request.user.file_two.path
    with open(demfile, newline='', encoding='latin-1') as f:

        reader = csv.reader(f, delimiter=';', skipinitialspace=True, strict=True)
        firstline = True
        for row in reader:
            if firstline:
                firstline = False
            else:
                material = row[1]
                oficina = row[0]
                txt_breve = row[2]
                product, created = Product.objects.get_or_create(material=material, owner=request.user,
                                                                 oficina=oficina,
                                                                 texto_breve_material=txt_breve)
                date_string = row[3]
                date = datetime.strptime(date_string, '%d/%m/%Y')
                mes_string = row[4]
                anno_string = row[5]
                demand_string = row[6]
                demand = int(demand_string)
                mes = int(mes_string)
                anno = int(anno_string)
                ProductDemand.objects.get_or_create(
                    product=product,
                    date=date,
                    mes=mes,
                    anno=anno,
                    demand=demand)

    with open(varfile, newline='') as f:

        reader = csv.reader(f, delimiter=';', skipinitialspace=True, strict=True)
        firstline = True
        for row in reader:
            if firstline:
                print(row)
                firstline = False
            else:
                if row[0] == '':
                    break

                tipo_de_producto = row[0]
                material = row[1]
                lead_time = int(float(row[2]))
                valor_r = float(row[3])
                valor_v = int(float((row[4])))
                valor_B1 = int(float((row[5])))
                valor_B2 = float(row[6])
                valor_B3 = float(row[7])
                valor_B4 = int(float((row[8])))
                valor_k = float(row[9])
                valor_a = int(float((row[10])))
                valor_p1 = float(row[11])
                valor_p2 = float(row[12])
                valor_sl = int(float((row[13])))
                valor_z = int(float((row[14])))
                valor_R2 = int(float((row[15])))
                valor_tbs = int(float((row[16])))
                prd = Product.objects.get(material=material, owner=request.user)
                prd.tipo_de_producto = tipo_de_producto
                prd.lead_time = lead_time
                prd.valor_r = valor_r
                prd.valor_z = valor_z
                prd.valor_tbs = valor_tbs
                prd.valor_R2 = valor_R2
                prd.valor_sl = valor_sl
                prd.valor_p2 = valor_p2
                prd.valor_p1 = valor_p1
                prd.valor_B4 = valor_B4
                prd.valor_B3 = valor_B3
                prd.valor_B2 = valor_B2
                prd.valor_B1 = valor_B1
                prd.valor_v = valor_v
                prd.valor_a = valor_a
                prd.valor_k = valor_k
                prd.save()
    print("termino la lectura")
    funcion_dma(request)
    calcular_EPQ(request)
    return render(request, 'toy_app/index.html')


@login_required
def funcion_dma(request):
    print("inicio demanda")
    p = Product.objects.filter(owner=request.user)
    f = open('DMA.txt', 'w')
    periodos = 60
    for product in p:
        all_demands = []
        dma = []
        sma = []
        n = 0
        y = []
        demanda_muestra = 0
        cont = 0
        for item in product.demands.all().order_by('date'):

            if cont < (len(product.demands.all()) - periodos):
                all_demands.append(item)
                demanda_muestra += item.demand
            else:
                product.demanda_promedio = demanda_muestra / cont
                break
            cont += 1

        while n + periodos - 1 < len(all_demands):
            aux = 0
            for i in range(n, n + periodos):
                aux = aux + all_demands[i].demand

                # (all_demands[n].demand + all_demands[n + 1].demand) / 2
            aux = aux / periodos
            sma.append(aux)
            n += 1
        n = 0
        while n - 1 + periodos < len(sma):
            aux = 0

            for i in range(n, n + periodos):
                aux = aux + sma[i]
            aux = aux / periodos
            dma.append(aux)
            n += 1
        a = ((2 * sma[-1]) - dma[-1])
        b = (2 * (sma[-1] - dma[-1]) / periodos)

        f.write(product.material + "\n")
        for num in range(1, periodos + 1):
            var = round(a + (num * b))
            y.append(var)
            PronosticoDMA.objects.get_or_create(owner=product, demanda_dma=var)

            f.write(str(var) + "\n")

    f.close()
    print("termino de calcular media movil doble")
    return render(request, 'toy_app/product_list.html')


@login_required
def metodo_ses(request):
    p = Product.objects.filter(owner=request.user)
    flag = True
    forecast = 0
    n = 1

    for i in p:
        lista = PronosticoSES.objects.filter(owner=i)
        for f in lista.monthly_demand:

            if len(f) == 12:
                if flag:
                    forecast = f[0]
                    flag = False
                else:
                    forecast = forecast * 0.9 * (f[n - 1] - forecast)
                    n += 1
        i.demanda_ses = forecast


class ProductView(ListView):
    # context_object_name = "productos"
    model = Product


def CalcularEOQ(request):
    p = Product.objects.filter(owner=request.user)
    f = open('EOQ.txt', 'w')
    for item in p:
        lote = LoteEcoOrden.objects.create(owner=item)
        lote.demand = item.demanda_promedio
        c = item.owner.valor_v
        h = item.owner.valor_r
        k = item.owner.valor_a
        root = (k * 2 * item.demanda_promedio) / h
        root = sqrt(root)
        lote.Q = root
        item.lote_orden = root
        lote.costo_p = k + c * root
        lote.mantener_inv = (h * root ** 2) / (2 * lote.demand)

        lote.save()
        item.save()
        f.write(root)


def calcular_EPQ(request):
    p = Product.objects.filter(owner=request.user)
    for item in p:
        lote = LoteEcoProd.objects.create(owner=item)
        lote.demand = item.demanda_promedio
        d = item.demanda_promedio
        c = item.owner.valor_v
        h = item.owner.valor_r
        k = item.owner.valor_a
        root = (k * 2 * item.demanda_promedio) / (h * (1 - (d / p)))
        root = sqrt(root)
        lote.Qprima = root
        item.lote_prod = root
        lote.save()
        item.save()


def calc_stats(request):
    p = Product.objects.filter(owner=request.user)
    for product in p:
        DMA = PronosticoDMA.objects.filter(owner=p)
        suma = 0
        for item in DMA:
            suma += item.demanda_dma

        D = product / len(DMA)
        H = product.valor_r
        K = product.valor_a
        Q = sqrt((K * 2 * D) / H)
        Q_prima = sqrt((K * 2 * D) / (H * (1 - (D / 1))))
        product.lote_orden = Q
        product.lote_prod = Q_prima
        product.save()


def get_data(request, *args, **kwargs):
    data = {
        "sales":200,
        "customer":20,
    }

    return JsonResponse(data, safe=False)


class ChartData(APIView):
    authentication_classes = []  # (authentication.TokenAuthentication,)
    permission_classes = []  # (permissions.IsAdminUser,)

    def get(self, request, format=None):

        data = {
            "sales": 200,
            "customers": 20,
            "users": User.objects.all().count()
        }
        return Response(data)

templates/toy_app/User_detail_view.html
{% extends 'toy_app/base.html' %}

{% block bodyblock %}
    <div class="jumbotron container">
        <h1>Product detail view</h1>
        <p>{{ product_detail.oficina }}</p>
        <p>{{ product_detail.texto_breve_material }}</p>
        <p>{{ product_detail.material }}</p>
        <p>{{ product_detail.tipo_de_producto }}</p>
        <p>{{ product_detail.demanda_dma }}</p>






    </div>

{% endblock %}

templates/toy_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title></title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="">

</head>
<body>

<div class="container">
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'index' %}">Homepage</a>
    {% if request.user.is_authenticated %}
        {% if request.user.is_superuser %}
            <a class="nav-link" href="{% url 'admin:index' %}" >ADMIN</a>
        {% endif %}
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'my_app:upload' pk=user.pk %}">Upload files</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'my_app:product_list' %}">Product list</a>
            </li>
            <li class="nav-item">
                <a class="nav-link logout" href="{% url 'logout' %}">Logout</a>
            </li>
            <span class="navbar-text">
                <h5>{{ request.user.email }}</h5>
            </span>
        </ul>
    {% else %}
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'login' %}">Login</a>
            </li>
            <li class="nav-item">
                <a class="nav-link " href="{% url 'signup' %}">signup</a>
            </li>
            <span class="navbar-text">
                No logeado
            </span>
        </ul>

    {% endif %}

  </nav>
</div>
{% block bodyblock %}

{% endblock %}
<div class="modal"></div>
</body>
</html>

templates/toy_app/chartdata.html
{% extends 'toy_app/base.html' %}

<script>
    {% block jquery %}
        alert("hola");
        var endpoint = {% url "api-data" %}
        $.ajax({
            method: "GET",
            url: endpoint,
            success: function(data) {
                console.log(data)
                console.log(data)
            },
            error: function (error_data) {
                console.log("Error")
                console.log(error_data)
                console.log("adsasdasdasdasd")
            }
        })
    {% endblock %}
</script>

{% block bodyblock %}
    <div class="container">
    <div class="col-sm-12 url-endpoint= '{% url "api-data" %}'>
         <h1>Hola mundo</h1>
        <canvas id="myChart" width="400" height="400"></canvas>

    </div>
    </div>

{% endblock %}

templates/toy_app/index.html
{% extends 'toy_app/base.html' %}

{% block title %}Login{% endblock %}

{% block bodyblock %}
    <div class="jumbotron container">
        <h1>Index</h1>
        <form >
            <input type="button" class="btn-btn-primary" name="boton" value="Click on me">
        </form>
    </div>
{% endblock %}

templates/toy_app/product_list.html
{% extends "toy_app/base.html" %}

{% block bodyblock %}

    <div class="container">
        <h1>Lista de productos</h1>
        <ol>
        {% for product in product_list %}
            {% if product.owner == user %}
                <h2><li><a href="{{ product.id }}">{{ product.material }}</a></li></h2>
            {% endif %}
        {% endfor %}
        </ol>
        <a class="button" href="{% url 'my_app:imprimir' %}"> leer archivo. </a>
        <a class="button" href="{% url 'my_app:dma' %}"> calcular media movil doble </a>
    </div>

        


{% endblock %}

templates/toy_app/user_form.html
{% extends 'toy_app/base.html' %}

{% block bodyblock %}
<div class="container"
    <h1>Ingrese los archivos requeridos.</h1>
    <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" class="btn btn-primary" value="Submit">
    </form>
</div>
{% endblock %}